echo "Copying required Files to EXEC:"
copy gfx/Levels/Level4	EXEC:
copy gfx/Levels/Char4	EXEC:
copy gfx/Panel		EXEC:
copy gfx/Menu		EXEC:
copy gfx/Font		EXEC:
copy gfx/PanelFont	EXEC:
copy gfx/Neon		EXEC:
copy gfx/RonnyBob	EXEC:
copy gfx/Level4Bob	EXEC:
copy gfx/ImmerBobs	EXEC:
copy gfx/HiScore	EXEC:
copy gfx/HowToPlay	EXEC:
copy gfx/HowToPlay2	EXEC:
copy gfx/HowToPlay3	EXEC:
copy sound/GameSong1	EXEC:
copy sound/SoundFX	EXEC:
copy HiNames		EXEC:
echo "The End ...."
